import dHexagonSentimentAnalysis as dHex
result=dHex.dHexagonAnalysis('/Users/akshayv/Desktop/sihaudio.wav')
print(f"graph coordinates->{result.coordinates}")
print(f"caller emotions->{result.emotions}")
print(f"call pos_percent->{result.pos_percent}")
print(f"call neg_percent->{result.neg_percent}")
print(f"call rating->{result.rating}")
print(f"call language->{result.language}")
print(f"call duration->{result.duration}")
print(f"caller gender->{result.gender}")